### PR TITLE
Upgrade to JSweet 2.0RC1

### PR DESCRIPTION
**Pull request by lln-ijinus**
Proposition to upgrade to the latest Jsweet.
I can't find any replacement to the setBundleDirectory, but it seems to work like this

### CODE REVIEW

**Comment by renaudpawlak** [comment]
Great! Many thanks :) I'll review ASAP.

**Comment by lgrignon** [comment]
Amazing, thanks

**Comment by renaudpawlak** [comment]
Done. Thanks again. I'll try to deploy it now.

**Comment by renaudpawlak** [comment]
I have deployed a new plugin version on the update site. Added the improvements of this [commit](https://github.com/cincheo/jsweet-eclipse-plugin/commit/2ebfc78872a2afb36e4114c92e707cce104dd839).

I have not tested the deployed version, so don't hesitate to tell me if you find something wrong (note that the project will require full clean/build and build path cleaning).

**Pull request merged**
